[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 921600
build_flags =
    -D POSEST_FIRMWARE_VERSION=\"0.1.0\"
    -Wall
    -Wextra
    -Wpedantic
    -Wshadow
    -Wconversion
    -Wsign-conversion
