#!/usr/bin/env bash
# Run Kalibr camera-IMU extrinsic calibration against one GuessWork
# extrinsics recording session, managing the Docker host (Colima) lifecycle
# so it's only running while Kalibr runs.
#
# Usage:
#   ./docker/kalibr/calibrate_imu.sh <session-dir> <num-cams> [model] [bag-freq-hz]
#
# <session-dir> must contain calibration.bag (with /cam0/image_raw …
# /cam{N-1}/image_raw and /imu0 topics), target.yaml, and imu.yaml — all
# produced by the extrinsics recording session. With num-cams == 1 it must
# additionally contain camchain.yaml (generated by the host from the
# camera's stored intrinsics); with num-cams >= 2 the camchain is solved
# fresh from the same bag via kalibr_calibrate_cameras first (intrinsics +
# cam-cam extrinsics), then fed to kalibr_calibrate_imu_camera.
#
# model (pair flow only) is the camera model for kalibr_calibrate_cameras:
# pinhole-radtan (default) or pinhole-equi for fisheye / wide-FOV lenses.
#
# bag-freq-hz subsamples the bag for the *cameras* step only (default 4;
# 0 = pass-through). kalibr_calibrate_imu_camera always consumes the full
# bag — the IMU optimization needs the unsubsampled motion.
#
# Env vars:
#   GW_KALIBR_FOCAL_HINT="<px0> <px1> …"
#     Optional per-camera focal hints in pixels (pair flow only), piped one
#     per line into Kalibr's manual-init prompts. See calibrate.sh for why.
#
# On success, camchain-imucam-calibration.yaml is written next to the bag
# (one camN block per camera with T_cam_imu + timeshift_cam_imu, plus
# T_cn_cnm1 on cam1+). The host's KalibrImuJob splits it per camera and
# stores each block against its camera row.

set -euo pipefail

SESSION="${1:-}"
NUM_CAMS="${2:-}"
MODEL="${3:-pinhole-radtan}"
BAG_FREQ="${4:-4}"
IMAGE="${GW_KALIBR_IMAGE:-guesswork/kalibr:latest}"
FOCAL_HINT="${GW_KALIBR_FOCAL_HINT:-}"
COLIMA_CPU="${COLIMA_CPU:-4}"
COLIMA_MEMORY="${COLIMA_MEMORY:-8}"
COLIMA_DISK="${COLIMA_DISK:-60}"
COLIMA_EXTRA=()
if [[ "$(uname -m)" == "arm64" ]]; then
    COLIMA_EXTRA=(--vm-type=vz --vz-rosetta)
fi

usage() {
    sed -n '2,31p' "$0" >&2
    exit 2
}

[[ -n "$SESSION" && -n "$NUM_CAMS" ]] || usage
[[ -d "$SESSION" ]]                 || { echo "session dir not found: $SESSION"  >&2; exit 2; }
[[ -f "$SESSION/calibration.bag" ]] || { echo "missing $SESSION/calibration.bag" >&2; exit 2; }
[[ -f "$SESSION/target.yaml" ]]     || { echo "missing $SESSION/target.yaml"     >&2; exit 2; }
[[ -f "$SESSION/imu.yaml" ]]        || { echo "missing $SESSION/imu.yaml"        >&2; exit 2; }

if ! [[ "$NUM_CAMS" =~ ^[0-9]+$ ]] || [[ "$NUM_CAMS" -lt 1 ]]; then
    echo "num-cams must be a positive integer (got: $NUM_CAMS)" >&2; exit 2
fi
if [[ "$NUM_CAMS" -eq 1 && ! -f "$SESSION/camchain.yaml" ]]; then
    echo "missing $SESSION/camchain.yaml (required for num-cams=1: generated" >&2
    echo "by the host from the camera's stored intrinsics)" >&2
    exit 2
fi

case "$MODEL" in
    pinhole-radtan|pinhole-equi) ;;
    *) echo "model must be pinhole-radtan or pinhole-equi (got: $MODEL)" >&2; exit 2 ;;
esac
if ! [[ "$BAG_FREQ" =~ ^[0-9]+$ ]]; then
    echo "bag-freq-hz must be a non-negative integer (got: $BAG_FREQ)" >&2; exit 2
fi
if [[ -n "$FOCAL_HINT" ]]; then
    for h in $FOCAL_HINT; do
        if ! [[ "$h" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
            echo "GW_KALIBR_FOCAL_HINT entries must be positive numbers (got: $h)" >&2
            exit 2
        fi
    done
fi

SESSION_ABS="$(cd "$SESSION" && pwd)"

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }

STARTED_COLIMA=0
cleanup() {
    if [[ $STARTED_COLIMA -eq 1 ]]; then
        log "stopping colima (we started it for this run)…"
        colima stop || true
    fi
}
trap cleanup EXIT

if ! docker info >/dev/null 2>&1; then
    if ! command -v colima >/dev/null 2>&1; then
        echo "docker socket not reachable and \`colima\` not on PATH." >&2
        echo "Install with: brew install colima docker" >&2
        exit 2
    fi
    log "docker socket not reachable — starting colima (cpu=$COLIMA_CPU memory=${COLIMA_MEMORY}G ${COLIMA_EXTRA[*]:-})…"
    colima start --cpu "$COLIMA_CPU" --memory "$COLIMA_MEMORY" --disk "$COLIMA_DISK" "${COLIMA_EXTRA[@]}"
    STARTED_COLIMA=1
fi

if ! docker image inspect "$IMAGE" >/dev/null 2>&1; then
    echo "Kalibr image $IMAGE not built." >&2
    echo "Run docker/kalibr/build.sh first (15-30 min, cached after)." >&2
    exit 2
fi

# Deterministic topic list: /cam0/image_raw … /cam{N-1}/image_raw — matches
# the host's MultiTopicBagRecorder connection ordering.
TOPICS=()
MODELS=()
for ((i = 0; i < NUM_CAMS; ++i)); do
    TOPICS+=("/cam${i}/image_raw")
    MODELS+=("$MODEL")
done

if [[ "$NUM_CAMS" -ge 2 ]]; then
    FREQ_ARGS=()
    if [[ "$BAG_FREQ" -gt 0 ]]; then
        FREQ_ARGS=(--bag-freq "$BAG_FREQ")
    fi
    log "step 1/2: kalibr_calibrate_cameras on $SESSION_ABS (${NUM_CAMS} cams, model=$MODEL)…"
    if [[ -n "$FOCAL_HINT" ]]; then
        # One hint per camera prompt, in topic order. Word splitting is
        # intentional — the env var is a space-separated list.
        printf '%s\n' $FOCAL_HINT | docker run --rm -i \
            -e KALIBR_MANUAL_FOCAL_LENGTH_INIT=1 \
            -v "$SESSION_ABS":/data \
            -w /data \
            "$IMAGE" \
            rosrun kalibr kalibr_calibrate_cameras \
                --bag /data/calibration.bag \
                --topics "${TOPICS[@]}" \
                --models "${MODELS[@]}" \
                --target /data/target.yaml \
                "${FREQ_ARGS[@]}"
    else
        docker run --rm \
            -v "$SESSION_ABS":/data \
            -w /data \
            "$IMAGE" \
            rosrun kalibr kalibr_calibrate_cameras \
                --bag /data/calibration.bag \
                --topics "${TOPICS[@]}" \
                --models "${MODELS[@]}" \
                --target /data/target.yaml \
                "${FREQ_ARGS[@]}"
    fi
    CHAIN="/data/calibration-camchain.yaml"
    [[ -f "$SESSION_ABS/calibration-camchain.yaml" ]] || {
        log "kalibr_calibrate_cameras finished but calibration-camchain.yaml was not produced."
        exit 1
    }
else
    CHAIN="/data/camchain.yaml"
fi

# Step 2: camera-IMU extrinsics. Our image and IMU stamps share the Teensy
# clock so the true time offset is ~0; the padding bounds optimizer
# excursions during estimation, not the answer.
log "step 2/2: kalibr_calibrate_imu_camera on $SESSION_ABS…"
docker run --rm \
    -v "$SESSION_ABS":/data \
    -w /data \
    "$IMAGE" \
    rosrun kalibr kalibr_calibrate_imu_camera \
        --bag /data/calibration.bag \
        --cam "$CHAIN" \
        --imu /data/imu.yaml \
        --target /data/target.yaml \
        --timeoffset-padding 0.1 \
        --dont-show-report

RESULT="$SESSION_ABS/camchain-imucam-calibration.yaml"
if [[ -f "$RESULT" ]]; then
    log "done. camchain-imucam: $RESULT"
else
    log "Kalibr finished but $RESULT was not produced — check the output above."
    exit 1
fi
