[platformio]
default_envs = micoair_f405_v2

[env:micoair_f405_v2]
platform = ststm32@19.7.1
board = genericSTM32F405RG
framework = arduino
upload_protocol = dfu
debug_tool = stlink
monitor_speed = 115200
build_unflags =
    -Os
build_flags =
    -O2
    -Wall
    -Wextra
    -Werror=return-type
    -D HSE_VALUE=8000000U
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D USBD_USE_CDC
    -D HAL_PCD_MODULE_ENABLED
    -D GW_BOARD_MICOAIR_F405_V2
